config/routes.rb
Rails.application.routes.draw do
  
  # Default
  root 'welcome#index'
  get 'about', to: 'pages#about'
  get 'home', to: 'pages#home'

  #articles
  resources :articles
  # Users
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  ##sessions
  get 'login', to: 'sessions#new'  
  post 'login', to: 'sessions#create'  
  delete 'logout', to: 'sessions#destroy'

  #categories
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    self.per_page = 2
    validates :title, presence: true, length: { minimum: 3, maximum:50 }
    validates :description, presence: true, length: { minimum: 10, maximum:300 }
    validates :user_id, presence: true

end

app/models/category.rb
class Category < ActiveRecord::Base
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    self.per_page = 10
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles, dependent: :destroy
    self.per_page = 2
    before_save { self.email = email.downcase }
    
    VALID_EMAIL_REGEX =  /\A(?=[A-Z0-9][A-Z0-9@._%+-]{5,253}+$)[A-Z0-9._%+-]{1,64}+@(?:(?=[A-Z0-9-]{1,63}+\.)[A-Z0-9]++(?:-[A-Z0-9]++)*+\.){1,8}+[A-Z]{2,63}+\z/i

    validates :username, uniqueness: { case_sensitive: false }, presence: true, length: { minimum: 3, maximum: 25 }
    validates :email, uniqueness: { case_sensitive: false }, presence: true, length: { minimum: 6, maximum: 50 },
                format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!current_user
    end
    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged to perform this action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page])
    end
    def new
        @article = Article.new
    end
    def edit
    end
    def update
        if @article.update(article_params)
            redirect_to article_path(@article), flash: { success: "Article was successfully updated!" }
            return
        else
            render 'new'
             return
        end
    end
    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            redirect_to article_path(@article), flash: { success: "Article was successfully created" }
            return
        else
            render 'new'
             return
        end
    end
    def show
        if Article.where(id: params[:id]).exists?(conditions = :none)
            set_article
        else
            redirect_to articles_path, flash: { danger: "There is no post with the id #{params[:id]}" }
        end
    end
    def destroy
        @article.destroy
        redirect_to articles_path, flash: { success: "Article was successfully deleted" }
    end
    private
        def set_article
            @article = Article.find(params[:id])
        end
        def article_params
            params.require(:article).permit(:title, :description)
        end
        def require_same_user
            if current_user != @article.user && !current_user.admin?
                flash[:danger] = "Restricted to articles created on your own"
                redirect_to root_path
            end
        end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, except: [:index, :show]

	def index
		@categories = Category.paginate(page: params[:page])
	end

	def new
		@category = Category.new
	end
	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category was created successfully"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def show

	end

	private
	def category_params
		params.require(:category).permit(:name)
	end
	def require_admin
		if !logged_in? || (logged_in? and !current_user.admin?)
			flash[:danger] = "Admins privileges required"
			redirect_to categories_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
    
    def about

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = 'You have successfuly logged in'
            redirect_to user_path(user)
            
        else
            flash.now[:danger] = 'There was something wrong with the login information'
            render 'new'
        end
    end
    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show, :destroy]
    before_action :require_same_user, only: [:edit, :update]
    before_action :require_admin, only: [:destroy]
    
    def index
        @users = User.paginate(page: params[:page])
    end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
            redirect_to user_path(session[:user_id])
        else
            render 'new'
        end
    end
    def edit
        
    end
    def update
        if @user.update(user_params)
            flash[:success] = "User updated successfully"
            redirect_to articles_path
        else
            render 'new'
        end
        
    end
    def show
        @user_articles = @user.articles.paginate(page: params[:page])
        @user_articles.per_page = 2
        
    end
    def destroy
        @user.destroy
        flash[:info] = "User and all articles created by user have been deleted"
        redirect_to users_path
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    def set_user
        @user = User.find(params[:id])
    end
    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "To edit another profiles is not allowed"
            redirect_to root_path
        end
    end
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Unauthorized action"
            redirect_to root_path
        end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        if logged_in?
            redirect_to articles_path
        else
            render 'index'
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article_list.html.erb
<% obj.each do |article|%>
    <div class="bg-light my-3 p-3 rounded">
      <h3 class="mt-3"><%= link_to  article.title, article_path(article), class: "text-dark" %></h3>
     
      <p><%= truncate(article.description, length: 100) %></p>
      <% if logged_in? && (current_user == article.user || current_user.admin?)%>
        <%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square mb-1" viewBox="0 0 16 16">
            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
            </svg> Edit'), edit_article_path(article), class: "btn btn-warning me-3" %>  
        
        <%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill mb-1" viewBox="0 0 16 16">
            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
            </svg> Delete'), article_path(article), method: :delete, data: {confirm: 'Are your sure?'}, class: 'btn btn-danger' %> 
      <% end %>
    </div>
<% end %>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <div class="container">
        <div class="alert alert-warning" role="alert">
            <h3>Check the following: </h3>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>


<%= form_for @article do |f| %>
    <div class="row mb-3">
        <div class="col-lg-3"><%= f.label :title, for: "title", class: "form-label" %></div>
        <div class="col-lg-9"><%= f.text_field :title,class: "form-control", id: "title", placeholder:"Enter the title" %></div>
    </div>
    <div class="row mb-3">
        <div class="col-lg-3"><%= f.label :description, for: "description", class: "form-label" %></div>
        <div class="col-lg-9"><%= f.text_field :description, class: "form-control", id: "description", placeholder:"Enter the description" %></div>
    </div>
    <div class="row mb-3">
        <%= f.submit class: "btn btn-primary" %> 
    </div>
<% end %>
    

<div class="text-center">
    [ <%= link_to "Back to articles listing", articles_path %> ]
</div>

app/views/articles/edit.html.erb
<div class="container">
    <h2 class="text-white bg-dark my-5 px-3 py-2 rounded">Modify the article: <span class="bg-danger px-2 rounded fs-4"><%= @article.id%></span></h2>
</div>
<div class="container bg-light p-5 rounded">
    <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h2 class="text-white bg-dark mt-5 mb-2 px-3 py-2 rounded">Articles List</h2>
  <nav class="d-flex justify-content-center mt-4">
    <%= will_paginate(renderer: BootstrapPagination::Rails) %>
  </nav>
  <%= render 'article_list', obj: @articles %>
  <nav class="d-flex justify-content-center my-4">
    <%= will_paginate(renderer: BootstrapPagination::Rails) %>
  </nav>

  <div class="text-center mt-3">
    <%= link_to 'Create a new Post', new_article_path, class: 'btn btn-primary me-3' %>
    <%= link_to 'Back to Home', root_path, class: 'btn btn-dark' %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
    <h2 class="text-white bg-dark my-5 px-3 py-2 rounded">Create a new article</h2>
</div>
<div class="container bg-light p-5 rounded">
    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
    <h2 class="text-white bg-dark mt-5 mb-2 px-3 py-2 rounded">
        <%= @article.title %>
    </h2>
    <div class="bg-light p-3 rounded">
        <p class="fs-6 lh-base"><%= @article.description %></p>
        <% if @article.user.articles %>
            <p class="mb-5 text-center">
                <strong>Published:</strong> <small class="text-success"><%= time_ago_in_words(@article.created_at) %></small> -
                <strong>@Author:</strong> <small class="text-info"><%= @article.user.username %></small> - 
                <span class="bg-danger text-white p-2 rounded"><%= pluralize(@article.user.articles.count, "article") %></span>
            </p>
        <% end %>
        
        <div class="text-center my-3">
            <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
                <%= link_to 'Edit this article', 
                edit_article_path(@article.id), 
                class: "btn btn-warning me-3" %> 
            <% end %>

            <%= link_to "Back to articles listing", 
            articles_path, 
            class: "btn btn-primary" %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="container mt-5">
    <h2 class="mb-3 bg-dark text-white rounded ps-3 py-2"><em>Listing All Categories</em></h2>

        <nav class="d-flex justify-content-center mt-4 mb-5">
            <%= will_paginate(renderer: BootstrapPagination::Rails) %>
        </nav>
        <div class="container d-flex flex-wrap justify-content-center w-50">
            <% @categories.each do |category| %>

                <%= link_to "#{category.name}", category_path(category), class: "btn btn-success px-2 rounded me-2 mb-3" %>

            <% end %>
        </div>
</div>

app/views/categories/new.html.erb
<div class="container mt-5">
    <% if @category.errors.any? %>
        <div class="container">
            <div class="alert alert-warning" role="alert">
                <h3>Check the following: </h3>
                <ul>
                    <% @category.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    <% end %>
    <h2 class="mb-3 bg-dark text-white rounded ps-3 py-2"><em>Create new category</em></h2>

    <%= form_for @category do |f| %>
        <div class="row mb-3">
            <div class="col-lg-3"><%= f.label :name, for: "name", class: "form-label" %></div>
            <div class="col-lg-9"><%= f.text_field :name,class: "form-control", id: "name", placeholder:"Enter category name" %></div>
        </div>
        <div class="row mb-3">
            <%= f.submit class: "btn btn-primary mt-3" %> 
        </div>
    <% end %>
    <div class="text-center">
        [ <%= link_to 'Cancel request and return to articles listing', articles_path %> ]
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="mt-5 py-2 border-top text-center text-info bg-dark">
  Rails © <%= Time.now.year %>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |type,msg| %>
    <div class="alert alert-<%= type %> alert-dismissible fade show my-3 rounded fs-6 text-center" role="alert">
      <strong><%= type.capitalize %>:</strong> <%= msg %>!
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
   <div class="container-fluid">
      <%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" 
          class="bi bi-braces" viewBox="0 0 16 16">
          <path d="M2.114 8.063V7.9c1.005-.102 1.497-.615 1.497-1.6V4.503c0-1.094.39-1.538 
          1.354-1.538h.273V2h-.376C3.25 2 2.49 2.759 2.49 4.352v1.524c0 1.094-.376 1.456-1.49 
          1.456v1.299c1.114 0 1.49.362 1.49 1.456v1.524c0 1.593.759 2.352 2.372 2.352h.376v-.964h-.273c-.964 
          0-1.354-.444-1.354-1.538V9.663c0-.984-.492-1.497-1.497-1.6zM13.886 7.9v.163c-1.005.103-1.497.616-1.497 
          1.6v1.798c0 1.094-.39 1.538-1.354 1.538h-.273v.964h.376c1.613 0 2.372-.759 
          2.372-2.352v-1.524c0-1.094.376-1.456 1.49-1.456V7.332c-1.114 0-1.49-.362-1.49-1.456V4.352C13.51 
          2.759 12.75 2 11.138 2h-.376v.964h.273c.964 0 1.354.444 1.354 1.538V6.3c0 .984.492 1.497 1.497 1.6z"/>
          </svg> <strong>Alpha-Blog</strong>'),root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" 
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to 'Articles',articles_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Users',users_path, class:"nav-link" %>
          </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="categories" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu mb-2 mb-lg-0" aria-labelledby="categories">
                <li>
                  <%= link_to 'View all',categories_path, class:"dropdown-item" %>
                </li>
          <% if logged_in? and current_user.admin? %>
                <li>
                  <%= link_to 'Create new category',new_category_path, class:"dropdown-item" %>
                </li>
          <% end %>
              </ul>
            </li>
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Articles
              </a>
              <ul class="dropdown-menu mb-2 mb-lg-0" aria-labelledby="navbarDropdownMenuLink">
                <li>
                  <%= link_to 'View all',articles_path, class:"dropdown-item" %>
                </li>
                <li>
                  <%= link_to 'Create new post',new_article_path, class:"dropdown-item" %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
        <form class="d-flex">
          <% if logged_in? %>
            <%= link_to 'Logout',logout_path, method: :delete, class:"btn btn-outline-danger me-2 mb-2 mb-lg-0" %>
            <div class="dropdown">
              <button class="btn btn-info dropdown-toggle" type="button" id="profile" data-bs-toggle="dropdown" aria-expanded="false">
                Your profile
              </button>
              <ul class="dropdown-menu mb-2 mb-lg-0" aria-labelledby="profile">
                <li>
                  <%= link_to 'Edit your profile',edit_user_path(current_user), class:"dropdown-item" %>
                </li>
                <li>
                  <%= link_to 'View your profile',user_path(current_user), class:"dropdown-item" %>
                </li>
              </ul>
            </div>
            
          <% else %>
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Access
              </button>
              <ul class="dropdown-menu mb-2 mb-lg-0" aria-labelledby="dropdownMenuButton1">
                <li>
                  <%= link_to 'Sign Up',signup_path, class:"dropdown-item" %>
                </li>
                <li>
                  <%= link_to 'Login',login_path, class:"dropdown-item" %>
                </li>
              </ul>
            </div>
          <% end %>
        </form>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  <%# <script>
    //fix bootstrap dropdown?
    $(document).ready(function () {
      $('.dropdown-toggle').dropdown()
    });
  </script> %>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the about page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>Welcome to the starting page</h1>

<%= link_to 'About', about_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <div class="row mb-3">
        <div class="col-lg-3"><%= f.label :username, for: "username", class: "form-label" %></div>
        <div class="col-lg-9"><%= f.text_field :username,class: "form-control", id: "username", placeholder:"Enter your username" %></div>
    </div>
    <div class="row mb-3">
        <div class="col-lg-3"><%= f.label :email, for: "email", class: "form-label" %></div>
        <div class="col-lg-9"><%= f.email_field :email,class: "form-control", id: "email", placeholder:"Enter your email" %></div>
    </div>
    <div class="row mb-3">
        <div class="col-lg-3"><%= f.label :password, for: "password", class: "form-label" %></div>
        <div class="col-lg-9"><%= f.password_field :password, class: "form-control", id: "password", placeholder:"Enter your password" %></div>
    </div>
    <div class="row mb-3">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update your profile", class: "btn btn-primary mt-3") %> 
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="container mt-5">
    <% if @user.errors.any? %>
        <div class="container">
            <div class="alert alert-warning" role="alert">
                <h3>Check the following: </h3>
                <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    <% end %>

    <h2 class="mb-3 text-center">Edit your profile settings</h2>

    <%= render 'form' %>

    <div class="text-center">
        [ <%= link_to 'Cancel request and return to articles listing', articles_path %> ]
    </div>
</div>

app/views/users/index.html.erb
<div class="container my-5 text-center">
    <h2 class="mb-3 bg-dark text-white rounded py-2"><em>Alpha Bloggers List</em></h2>
    <nav class="d-flex justify-content-center mt-4 mb-5">
        <%= will_paginate(renderer: BootstrapPagination::Rails) %>
    </nav>
    <% @users.each do |user| %>
        <div class="row text-center bg-light rounded py-2 mb-3">
            <div class="col-4 d-flex justify-content-center align-items-center">
                <%= link_to gravatar_for(user, size: 80), user_path(user) %>
            </div>
            <div class="col-4 fs-3 bg-warning rounded py-3 d-flex justify-content-center align-items-center">
                <em><%= link_to user.username, user_path(user), class: "text-dark" %></em>
            </div>
            <div class="col-4 d-flex flex-column justify-content-around align-items-around">
                <span class="bg-success text-white p-2 rounded">
                    <%= pluralize(user.articles.count, "article") if user.articles %>
                </span>
                <% if logged_in? && current_user.admin? %>
                    <%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill mb-1" viewBox="0 0 16 16">
                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                        </svg> Delete User'), user_path(user), method: :delete, data: {confirm: 'Are your sure?'}, class: 'btn btn-danger' %> 
                <% end %>
            </div>
        </div>
    <% end %>
    <nav class="d-flex justify-content-center mt-5 mb-4">
        <%= will_paginate(renderer: BootstrapPagination::Rails) %>
    </nav>
</div>

app/views/users/new.html.erb
<div class="container mt-5">
    <% if @user.errors.any? %>
        <div class="container">
            <div class="alert alert-warning" role="alert">
                <h3>Check the following: </h3>
                <ul>
                    <% @user.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    <% end %>

    <h2 class="mb-3 text-center">Sign Up for Alpha Blog</h2>

    <%= form_for @user do |f| %>
        <div class="row mb-3">
            <div class="col-lg-3"><%= f.label :username, for: "username", class: "form-label" %></div>
            <div class="col-lg-9"><%= f.text_field :username,class: "form-control", id: "username", placeholder:"Enter your username" %></div>
        </div>
        <div class="row mb-3">
            <div class="col-lg-3"><%= f.label :email, for: "email", class: "form-label" %></div>
            <div class="col-lg-9"><%= f.email_field :email,class: "form-control", id: "email", placeholder:"Enter your email" %></div>
        </div>
        <div class="row mb-3">
            <div class="col-lg-3"><%= f.label :password, for: "password", class: "form-label" %></div>
            <div class="col-lg-9"><%= f.password_field :password, class: "form-control", id: "password", placeholder:"Enter your password" %></div>
        </div>
        <div class="row mb-3">
            <%= f.submit 'Sign Up', class: "btn btn-primary mt-3" %> 
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="container text-center my-5">
    <h2>Welcome to <strong class="text-info"><%= @user.username %>'s</strong> page</h2>

    <div class="row my-3">
        <div class="col-12 text-center">
            <%= gravatar_for @user, size: 150 %>
        </div>
    </div>

    <h3><%= @user.username %>'s articles</h3>
    
    <nav class="d-flex justify-content-center mt-5 mb-4">
        <%= will_paginate(@user_articles, renderer: BootstrapPagination::Rails) %>
    </nav>
    <%= render 'articles/article_list', obj: @user_articles %>
</div>

app/views/welcome/index.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5 text-center">
    <h1 class="display-5 fw-bold">Custom jumbotron</h1>
    <p>Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap.</p>
    <%= link_to 'Sign-Up', signup_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>